---
version: 3
dependencies:
  galaxy: requirements.yml
  python:
    - six
    - psutil
  system:
    - python3-pip
    - python3-setuptools
images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest
options:
  package_manager_path: /usr/bin/microdnf
